### ISSUE TITLE
Multiple chat windows?

### ISSUE THREAD

**Issue by danielbsig** [irontec/angular-bootstrap-simple-chat#1]
Does this control support multiple instances of the chat window?

**Comment by Kaian** [comment]
Ups, bad project. Sorry for the response.

**Comment by aitorllj93** [comment]
Hi! I think it should, but haven't tested. I will give a try and answer you with the result :)

**Comment by danielbsig** [comment]
Thanks!

**Comment by aitorllj93** [comment]
Hi again! I tried with two instances and works well, but there is a little thing to have in mind:
By default, the chat gets rendered in the bottom-right of the page, with this css

``` css
// Chat Window Class
.chat-window {
  bottom: 0;
  float: right;
  margin-left: 10px;
  position: fixed;
  right: 0;
  z-index: 9999;
}
```

So, all the chat directives you load in the same page, will be rendered in the same position, and the second directive will overlay the first one.

To avoid this, you can write your own css for the second chat, assigning to it a css class, id or custom theme.

Sample:

``` css
#left {
  position: fixed;
  left: 0;
}
```
